env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: build plugin

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        id: checkout-source
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - run: mvn --batch-mode clean package
        name: build plugins
      - uses: actions/upload-artifact@v3
        name: 'upload plugins'
        with:
          name: 'Plugin'
          path: 'target/'